version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=https://db06-207-140-25-4.ngrok-free.app
  ngrok:
    image: ngrok/ngrok:latest
    command: http --subdomain="saamainfer" frontend:3000
    ports:
      - "4041:4040"
    environment:
      NGROK_AUTHTOKEN: