import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { SidebarNav } from "@/components/SidebarNav";
import { AppHeader } from "@/components/AppHeader";
import { StudyDataProvider } from "@/context/StudyDataContext";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Saama Infer App",
  description: "Generated by Saama Tech Inc",
};

export default function RootLayout({ children }: { children: ReactNode }) {

    return (
        <html lang="en">
        <body className="bg-gradient-to-br from-gray-50 to-gray-100 text-gray-900">
        <Toaster richColors position="top-center" />
        <StudyDataProvider>
        <div className="flex flex-col h-screen">
            <AppHeader /> {/* Stays at top */}
            <div className="flex flex-1 overflow-hidden">
                <SidebarNav /> {/* Stays at left */}
                <main className="flex-1 overflow-y-auto p-6">
                    {children} {/* This is scrollable */}
                </main>
            </div>
        </div>
        </StudyDataProvider>
        </body>
        </html>
    );
}
